/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param input The input texts for generating clusters
 * @param clusterCount The number of clusters requested for generating clusters
 * @param maxDegreeOfParallelism The maximum degree of parallelism for the KMeans clustering algorithm
 * @param maxTokens The maximum number of tokens
 * @param llmModel The name of the LLM model. Optional.
 * @param embeddingModel The name of the embedding model used in the GenerateClusterHttpRequest. Optional.
 * @param seed Randomization seed. Optional.
 */


data class ApiExtractThematicSimilarityClusterPostRequest (

    /* The input texts for generating clusters */
    @Json(name = "input")
    val input: kotlin.collections.List<kotlin.String>,

    /* The number of clusters requested for generating clusters */
    @Json(name = "clusterCount")
    val clusterCount: kotlin.Int,

    /* The maximum degree of parallelism for the KMeans clustering algorithm */
    @Json(name = "maxDegreeOfParallelism")
    val maxDegreeOfParallelism: kotlin.Int? = 1,

    /* The maximum number of tokens */
    @Json(name = "maxTokens")
    val maxTokens: kotlin.Int? = 10,

    /* The name of the LLM model. Optional. */
    @Json(name = "llmModel")
    val llmModel: kotlin.String? = null,

    /* The name of the embedding model used in the GenerateClusterHttpRequest. Optional. */
    @Json(name = "embeddingModel")
    val embeddingModel: kotlin.String? = null,

    /* Randomization seed. Optional. */
    @Json(name = "seed")
    val seed: kotlin.Int? = null

) {


}

