/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param documentId Id that uniquely identifies content. Previously ingested documents with the same id will be overwritten
 * @param text Text to ingest
 * @param index Optional value to specify with index the document should be ingested. Defaults to 'default'
 * @param tags Optionally add tags to ingestion
 * @param pipeline Optional value to specify ingestion pipeline steps. Defaults to server configured defaults.
 * @param webHookUrl Url to use for webhook callback when operation finishes or fails.
 * @param embeddingModel Embedding model to use in ingestion. Optional. Default to configured default.
 * @param args 
 */


data class IngestTextDocumentRequest (

    /* Id that uniquely identifies content. Previously ingested documents with the same id will be overwritten */
    @Json(name = "documentId")
    val documentId: kotlin.String,

    /* Text to ingest */
    @Json(name = "text")
    val text: kotlin.String,

    /* Optional value to specify with index the document should be ingested. Defaults to 'default' */
    @Json(name = "index")
    val index: kotlin.String? = null,

    /* Optionally add tags to ingestion */
    @Json(name = "tags")
    val tags: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null,

    /* Optional value to specify ingestion pipeline steps. Defaults to server configured defaults. */
    @Json(name = "pipeline")
    val pipeline: kotlin.collections.List<kotlin.String>? = null,

    /* Url to use for webhook callback when operation finishes or fails. */
    @Json(name = "webHookUrl")
    val webHookUrl: kotlin.String? = null,

    /* Embedding model to use in ingestion. Optional. Default to configured default. */
    @Json(name = "embeddingModel")
    val embeddingModel: kotlin.String? = null,

    @Json(name = "args")
    val args: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

