/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Citation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param query 
 * @param noResult 
 * @param results 
 */


data class SearchResult (

    @Json(name = "query")
    val query: kotlin.String? = null,

    @Json(name = "noResult")
    val noResult: kotlin.Boolean? = null,

    @Json(name = "results")
    val results: kotlin.collections.List<Citation>? = null

) {


}

