/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a translation request with the source text, source language, and target language.
 *
 * @param text The input text to be translated.
 * @param source The language code of the input text.
 * @param target The language code of the desired output translation.
 */


data class Translate (

    /* The input text to be translated. */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* The language code of the input text. */
    @Json(name = "source")
    val source: Translate.Source? = null,

    /* The language code of the desired output translation. */
    @Json(name = "target")
    val target: Translate.Target? = null

) {

    /**
     * The language code of the input text.
     *
     * Values: auto,ar,az,bg,bn,ca,cs,da,de,el,en,eo,es,et,fa,fi,fr,ga,he,hi,hu,id,`it`,ja,ko,lt,lv,ms,nb,nl,pl,pt,ro,ru,sk,sl,sq,sv,th,tl,tr,uk,zh,zt
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "auto") auto("auto"),
        @Json(name = "ar") ar("ar"),
        @Json(name = "az") az("az"),
        @Json(name = "bg") bg("bg"),
        @Json(name = "bn") bn("bn"),
        @Json(name = "ca") ca("ca"),
        @Json(name = "cs") cs("cs"),
        @Json(name = "da") da("da"),
        @Json(name = "de") de("de"),
        @Json(name = "el") el("el"),
        @Json(name = "en") en("en"),
        @Json(name = "eo") eo("eo"),
        @Json(name = "es") es("es"),
        @Json(name = "et") et("et"),
        @Json(name = "fa") fa("fa"),
        @Json(name = "fi") fi("fi"),
        @Json(name = "fr") fr("fr"),
        @Json(name = "ga") ga("ga"),
        @Json(name = "he") he("he"),
        @Json(name = "hi") hi("hi"),
        @Json(name = "hu") hu("hu"),
        @Json(name = "id") id("id"),
        @Json(name = "it") `it`("it"),
        @Json(name = "ja") ja("ja"),
        @Json(name = "ko") ko("ko"),
        @Json(name = "lt") lt("lt"),
        @Json(name = "lv") lv("lv"),
        @Json(name = "ms") ms("ms"),
        @Json(name = "nb") nb("nb"),
        @Json(name = "nl") nl("nl"),
        @Json(name = "pl") pl("pl"),
        @Json(name = "pt") pt("pt"),
        @Json(name = "ro") ro("ro"),
        @Json(name = "ru") ru("ru"),
        @Json(name = "sk") sk("sk"),
        @Json(name = "sl") sl("sl"),
        @Json(name = "sq") sq("sq"),
        @Json(name = "sv") sv("sv"),
        @Json(name = "th") th("th"),
        @Json(name = "tl") tl("tl"),
        @Json(name = "tr") tr("tr"),
        @Json(name = "uk") uk("uk"),
        @Json(name = "zh") zh("zh"),
        @Json(name = "zt") zt("zt");
    }
    /**
     * The language code of the desired output translation.
     *
     * Values: ar,az,bg,bn,ca,cs,da,de,el,en,eo,es,et,fa,fi,fr,ga,he,hi,hu,id,`it`,ja,ko,lt,lv,ms,nb,nl,pl,pt,ro,ru,sk,sl,sq,sv,th,tl,tr,uk,zh,zt
     */
    @JsonClass(generateAdapter = false)
    enum class Target(val value: kotlin.String) {
        @Json(name = "ar") ar("ar"),
        @Json(name = "az") az("az"),
        @Json(name = "bg") bg("bg"),
        @Json(name = "bn") bn("bn"),
        @Json(name = "ca") ca("ca"),
        @Json(name = "cs") cs("cs"),
        @Json(name = "da") da("da"),
        @Json(name = "de") de("de"),
        @Json(name = "el") el("el"),
        @Json(name = "en") en("en"),
        @Json(name = "eo") eo("eo"),
        @Json(name = "es") es("es"),
        @Json(name = "et") et("et"),
        @Json(name = "fa") fa("fa"),
        @Json(name = "fi") fi("fi"),
        @Json(name = "fr") fr("fr"),
        @Json(name = "ga") ga("ga"),
        @Json(name = "he") he("he"),
        @Json(name = "hi") hi("hi"),
        @Json(name = "hu") hu("hu"),
        @Json(name = "id") id("id"),
        @Json(name = "it") `it`("it"),
        @Json(name = "ja") ja("ja"),
        @Json(name = "ko") ko("ko"),
        @Json(name = "lt") lt("lt"),
        @Json(name = "lv") lv("lv"),
        @Json(name = "ms") ms("ms"),
        @Json(name = "nb") nb("nb"),
        @Json(name = "nl") nl("nl"),
        @Json(name = "pl") pl("pl"),
        @Json(name = "pt") pt("pt"),
        @Json(name = "ro") ro("ro"),
        @Json(name = "ru") ru("ru"),
        @Json(name = "sk") sk("sk"),
        @Json(name = "sl") sl("sl"),
        @Json(name = "sq") sq("sq"),
        @Json(name = "sv") sv("sv"),
        @Json(name = "th") th("th"),
        @Json(name = "tl") tl("tl"),
        @Json(name = "tr") tr("tr"),
        @Json(name = "uk") uk("uk"),
        @Json(name = "zh") zh("zh"),
        @Json(name = "zt") zt("zt");
    }

}

