version: "3"
services:
  chat-copilot-webapp:
   image: esbencarlsen/chat-copilot-webapp
   ports:
     - 3000:3000
   environment:
     - REACT_APP_BACKEND_URI=http://localhost:3080
   depends_on:
     chat-copilot-webapi:
       condition: service_started
  chat-copilot-webapi:
    image: esbencarlsen/chat-copilot-webapi
    ports:
      - 3080:8080
    environment:
      - Authentication__Type=none
