services:
  chat-copilot-webapp:
    container_name: chat-copilot-webapp
    image: chat-copilot-webapp
    build:
      context: ..
      dockerfile: docker/webapp/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URI=http://localhost:3080
    depends_on:
      chat-copilot-webapi:
        condition: service_started
  chat-copilot-webapi:
    container_name: chat-copilot-webapi
    image: chat-copilot-webapi
    build:
      context: ..
      dockerfile: docker/webapi/Dockerfile
    ports:
      - "3080:8080"
    volumes:
      - ./webapi/appsettings.json:/app/appsettings.json # Mounts a configuration file into the container
    env_file:
      - ./webapi/.env
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;User Id=$POSTGRES_USER;Database=$POSTGRES_DB;Password=$POSTGRES_PASSWORD;Pooling=true
    depends_on:
      postgres:
        condition: service_started
  postgres:
    container_name: chat-copilot-postgres
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
