/**
 * Studio - AI Empower Labs
 * # Studio API Documentation  ## Introduction Welcome to Studio by AI Empower Labs API documentation! We are thrilled to offer developers around the world access to our cutting-edge artificial intelligence technology and semantic search. Our API is designed to empower your applications with state-of-the-art AI capabilities, including but not limited to natural language processing, audio transcription, embedding, and predictive analytics.  Our mission is to make AI technology accessible and easy to integrate, enabling you to enhance your applications, improve user experiences, and innovate in your field. Whether you're building complex systems, developing mobile apps, or creating web services, our API provides you with the tools you need to incorporate AI functionalities seamlessly.  Support and Feedback We are committed to providing exceptional support to our developer community. If you have any questions, encounter any issues, or have feedback on how we can improve our API, please don't hesitate to contact our support team @ support@AIEmpowerLabs.com.  Terms of Use Please review our terms of use and privacy policy before integrating our API into your application. By using our API, you agree to comply with these terms.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@aiempowerlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StudioAiEmpowerLabs);
  }
}(this, function(expect, StudioAiEmpowerLabs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StudioAiEmpowerLabs.SemanticSearchApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SemanticSearchApi', function() {
    describe('semanticSearchAsk', function() {
      it('should call semanticSearchAsk successfully', function(done) {
        //uncomment below and update the code to test semanticSearchAsk
        //instance.semanticSearchAsk(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchDeleteDocument', function() {
      it('should call semanticSearchDeleteDocument successfully', function(done) {
        //uncomment below and update the code to test semanticSearchDeleteDocument
        //instance.semanticSearchDeleteDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchDeleteIndex', function() {
      it('should call semanticSearchDeleteIndex successfully', function(done) {
        //uncomment below and update the code to test semanticSearchDeleteIndex
        //instance.semanticSearchDeleteIndex(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchFileIngestion', function() {
      it('should call semanticSearchFileIngestion successfully', function(done) {
        //uncomment below and update the code to test semanticSearchFileIngestion
        //instance.semanticSearchFileIngestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchIngestionStatus', function() {
      it('should call semanticSearchIngestionStatus successfully', function(done) {
        //uncomment below and update the code to test semanticSearchIngestionStatus
        //instance.semanticSearchIngestionStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchList', function() {
      it('should call semanticSearchList successfully', function(done) {
        //uncomment below and update the code to test semanticSearchList
        //instance.semanticSearchList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchQuery', function() {
      it('should call semanticSearchQuery successfully', function(done) {
        //uncomment below and update the code to test semanticSearchQuery
        //instance.semanticSearchQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchRerank', function() {
      it('should call semanticSearchRerank successfully', function(done) {
        //uncomment below and update the code to test semanticSearchRerank
        //instance.semanticSearchRerank(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchTextIngestion', function() {
      it('should call semanticSearchTextIngestion successfully', function(done) {
        //uncomment below and update the code to test semanticSearchTextIngestion
        //instance.semanticSearchTextIngestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('semanticSearchWebpageIngestion', function() {
      it('should call semanticSearchWebpageIngestion successfully', function(done) {
        //uncomment below and update the code to test semanticSearchWebpageIngestion
        //instance.semanticSearchWebpageIngestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
