# coding: utf-8

"""
    Studio - AI Empower Labs

    # Studio API Documentation  ## Introduction Welcome to Studio by AI Empower Labs API documentation! We are thrilled to offer developers around the world access to our cutting-edge artificial intelligence technology and semantic search. Our API is designed to empower your applications with state-of-the-art AI capabilities, including but not limited to natural language processing, audio transcription, embedding, and predictive analytics.  Our mission is to make AI technology accessible and easy to integrate, enabling you to enhance your applications, improve user experiences, and innovate in your field. Whether you're building complex systems, developing mobile apps, or creating web services, our API provides you with the tools you need to incorporate AI functionalities seamlessly.  Support and Feedback We are committed to providing exceptional support to our developer community. If you have any questions, encounter any issues, or have feedback on how we can improve our API, please don't hesitate to contact our support team @ support@AIEmpowerLabs.com.  Terms of Use Please review our terms of use and privacy policy before integrating our API into your application. By using our API, you agree to comply with these terms.

    The version of the OpenAPI document: v1
    Contact: support@aiempowerlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.document_partition import DocumentPartition
from typing import Optional, Set
from typing_extensions import Self

class DocumentCitation(BaseModel):
    """
    DocumentCitation
    """ # noqa: E501
    link: Optional[StrictStr] = Field(default=None, description="Link to the source, if available.")
    index: Optional[StrictStr] = Field(default=None, description="Link to the source, if available.")
    document_id: Optional[StrictStr] = Field(default=None, description="Link to the source, if available.", alias="documentId")
    file_id: Optional[StrictStr] = Field(default=None, description="Link to the source, if available.", alias="fileId")
    source_content_type: Optional[StrictStr] = Field(default=None, description="Type of source, e.g. PDF, Word, Chat, etc.", alias="sourceContentType")
    source_name: Optional[StrictStr] = Field(default=None, description="Name of the source, e.g. file name.", alias="sourceName")
    source_url: Optional[StrictStr] = Field(default=None, description="URL of the source, used for web pages and external data", alias="sourceUrl")
    partitions: Optional[List[DocumentPartition]] = Field(default=None, description="List of chunks/blocks of text used.")
    __properties: ClassVar[List[str]] = ["link", "index", "documentId", "fileId", "sourceContentType", "sourceName", "sourceUrl", "partitions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentCitation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in partitions (list)
        _items = []
        if self.partitions:
            for _item_partitions in self.partitions:
                if _item_partitions:
                    _items.append(_item_partitions.to_dict())
            _dict['partitions'] = _items
        # set to None if link (nullable) is None
        # and model_fields_set contains the field
        if self.link is None and "link" in self.model_fields_set:
            _dict['link'] = None

        # set to None if index (nullable) is None
        # and model_fields_set contains the field
        if self.index is None and "index" in self.model_fields_set:
            _dict['index'] = None

        # set to None if document_id (nullable) is None
        # and model_fields_set contains the field
        if self.document_id is None and "document_id" in self.model_fields_set:
            _dict['documentId'] = None

        # set to None if file_id (nullable) is None
        # and model_fields_set contains the field
        if self.file_id is None and "file_id" in self.model_fields_set:
            _dict['fileId'] = None

        # set to None if source_content_type (nullable) is None
        # and model_fields_set contains the field
        if self.source_content_type is None and "source_content_type" in self.model_fields_set:
            _dict['sourceContentType'] = None

        # set to None if source_name (nullable) is None
        # and model_fields_set contains the field
        if self.source_name is None and "source_name" in self.model_fields_set:
            _dict['sourceName'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['sourceUrl'] = None

        # set to None if partitions (nullable) is None
        # and model_fields_set contains the field
        if self.partitions is None and "partitions" in self.model_fields_set:
            _dict['partitions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentCitation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "link": obj.get("link"),
            "index": obj.get("index"),
            "documentId": obj.get("documentId"),
            "fileId": obj.get("fileId"),
            "sourceContentType": obj.get("sourceContentType"),
            "sourceName": obj.get("sourceName"),
            "sourceUrl": obj.get("sourceUrl"),
            "partitions": [DocumentPartition.from_dict(_item) for _item in obj["partitions"]] if obj.get("partitions") is not None else None
        })
        return _obj


