/**
 * Studio - AI Empower Labs
 * # Studio API Documentation  ## Introduction Welcome to Studio by AI Empower Labs API documentation! We are thrilled to offer developers around the world access to our cutting-edge artificial intelligence technology and semantic search. Our API is designed to empower your applications with state-of-the-art AI capabilities, including but not limited to natural language processing, audio transcription, embedding, and predictive analytics.  Our mission is to make AI technology accessible and easy to integrate, enabling you to enhance your applications, improve user experiences, and innovate in your field. Whether you're building complex systems, developing mobile apps, or creating web services, our API provides you with the tools you need to incorporate AI functionalities seamlessly.  Support and Feedback We are committed to providing exceptional support to our developer community. If you have any questions, encounter any issues, or have feedback on how we can improve our API, please don't hesitate to contact our support team @ support@AIEmpowerLabs.com.  Terms of Use Please review our terms of use and privacy policy before integrating our API into your application. By using our API, you agree to comply with these terms.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@aiempowerlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IngestWebPageDocumentRequest model module.
 * @module model/IngestWebPageDocumentRequest
 * @version v1
 */
class IngestWebPageDocumentRequest {
    /**
     * Constructs a new <code>IngestWebPageDocumentRequest</code>.
     * @alias module:model/IngestWebPageDocumentRequest
     * @param url {String} Web page to ingest
     * @param documentId {String} Unique identifier for the document to ingest.
     */
    constructor(url, documentId) { 
        
        IngestWebPageDocumentRequest.initialize(this, url, documentId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, documentId) { 
        obj['url'] = url;
        obj['documentId'] = documentId;
        obj['languageAutoDetection'] = false;
    }

    /**
     * Constructs a <code>IngestWebPageDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngestWebPageDocumentRequest} obj Optional instance to populate.
     * @return {module:model/IngestWebPageDocumentRequest} The populated <code>IngestWebPageDocumentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngestWebPageDocumentRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'String');
            }
            if (data.hasOwnProperty('webHookUrl')) {
                obj['webHookUrl'] = ApiClient.convertToType(data['webHookUrl'], 'String');
            }
            if (data.hasOwnProperty('embeddingModelName')) {
                obj['embeddingModelName'] = ApiClient.convertToType(data['embeddingModelName'], 'String');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = ApiClient.convertToType(data['context'], {'String': 'String'});
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], {'String': ['String']});
            }
            if (data.hasOwnProperty('ingestionPipeline')) {
                obj['ingestionPipeline'] = ApiClient.convertToType(data['ingestionPipeline'], ['String']);
            }
            if (data.hasOwnProperty('languageAutoDetection')) {
                obj['languageAutoDetection'] = ApiClient.convertToType(data['languageAutoDetection'], 'Boolean');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IngestWebPageDocumentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IngestWebPageDocumentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IngestWebPageDocumentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['documentId'] && !(typeof data['documentId'] === 'string' || data['documentId'] instanceof String)) {
            throw new Error("Expected the field `documentId` to be a primitive type in the JSON string but got " + data['documentId']);
        }
        // ensure the json data is a string
        if (data['index'] && !(typeof data['index'] === 'string' || data['index'] instanceof String)) {
            throw new Error("Expected the field `index` to be a primitive type in the JSON string but got " + data['index']);
        }
        // ensure the json data is a string
        if (data['webHookUrl'] && !(typeof data['webHookUrl'] === 'string' || data['webHookUrl'] instanceof String)) {
            throw new Error("Expected the field `webHookUrl` to be a primitive type in the JSON string but got " + data['webHookUrl']);
        }
        // ensure the json data is a string
        if (data['embeddingModelName'] && !(typeof data['embeddingModelName'] === 'string' || data['embeddingModelName'] instanceof String)) {
            throw new Error("Expected the field `embeddingModelName` to be a primitive type in the JSON string but got " + data['embeddingModelName']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['ingestionPipeline'])) {
            throw new Error("Expected the field `ingestionPipeline` to be an array in the JSON data but got " + data['ingestionPipeline']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }

        return true;
    }


}

IngestWebPageDocumentRequest.RequiredProperties = ["url", "documentId"];

/**
 * Web page to ingest
 * @member {String} url
 */
IngestWebPageDocumentRequest.prototype['url'] = undefined;

/**
 * Unique identifier for the document to ingest.
 * @member {String} documentId
 */
IngestWebPageDocumentRequest.prototype['documentId'] = undefined;

/**
 * Optional index name where the document will be stored.
 * @member {String} index
 */
IngestWebPageDocumentRequest.prototype['index'] = undefined;

/**
 * Optional webhook URL to notify upon completion.
 * @member {String} webHookUrl
 */
IngestWebPageDocumentRequest.prototype['webHookUrl'] = undefined;

/**
 * Optional name of the embedding model to use during ingestion.
 * @member {String} embeddingModelName
 */
IngestWebPageDocumentRequest.prototype['embeddingModelName'] = undefined;

/**
 * Optional key-value pairs for additional context or metadata.
 * @member {Object.<String, String>} context
 */
IngestWebPageDocumentRequest.prototype['context'] = undefined;

/**
 * A collection of tags associated with the document. Tags can be language-specific.
 * @member {Object.<String, Array.<String>>} tags
 */
IngestWebPageDocumentRequest.prototype['tags'] = undefined;

/**
 * Optional list of ingestion pipeline steps. Allows custom processing.
 * @member {Array.<String>} ingestionPipeline
 */
IngestWebPageDocumentRequest.prototype['ingestionPipeline'] = undefined;

/**
 * Enable automatic language detection for document content.
 * @member {Boolean} languageAutoDetection
 * @default false
 */
IngestWebPageDocumentRequest.prototype['languageAutoDetection'] = false;

/**
 * Force a specific language for full-text search. Use 'simple' for no language or leave empty.
 * @member {module:model/IngestWebPageDocumentRequest.LanguageEnum} language
 */
IngestWebPageDocumentRequest.prototype['language'] = undefined;





/**
 * Allowed values for the <code>language</code> property.
 * @enum {String}
 * @readonly
 */
IngestWebPageDocumentRequest['LanguageEnum'] = {

    /**
     * value: "arabic"
     * @const
     */
    "arabic": "arabic",

    /**
     * value: "armenian"
     * @const
     */
    "armenian": "armenian",

    /**
     * value: "basque"
     * @const
     */
    "basque": "basque",

    /**
     * value: "catalan"
     * @const
     */
    "catalan": "catalan",

    /**
     * value: "danish"
     * @const
     */
    "danish": "danish",

    /**
     * value: "dutch"
     * @const
     */
    "dutch": "dutch",

    /**
     * value: "english"
     * @const
     */
    "english": "english",

    /**
     * value: "finnish"
     * @const
     */
    "finnish": "finnish",

    /**
     * value: "french"
     * @const
     */
    "french": "french",

    /**
     * value: "german"
     * @const
     */
    "german": "german",

    /**
     * value: "greek"
     * @const
     */
    "greek": "greek",

    /**
     * value: "hindi"
     * @const
     */
    "hindi": "hindi",

    /**
     * value: "hungarian"
     * @const
     */
    "hungarian": "hungarian",

    /**
     * value: "indonesian"
     * @const
     */
    "indonesian": "indonesian",

    /**
     * value: "irish"
     * @const
     */
    "irish": "irish",

    /**
     * value: "italian"
     * @const
     */
    "italian": "italian",

    /**
     * value: "lithuanian"
     * @const
     */
    "lithuanian": "lithuanian",

    /**
     * value: "nepali"
     * @const
     */
    "nepali": "nepali",

    /**
     * value: "norwegian"
     * @const
     */
    "norwegian": "norwegian",

    /**
     * value: "portuguese"
     * @const
     */
    "portuguese": "portuguese",

    /**
     * value: "romanian"
     * @const
     */
    "romanian": "romanian",

    /**
     * value: "russian"
     * @const
     */
    "russian": "russian",

    /**
     * value: "serbian"
     * @const
     */
    "serbian": "serbian",

    /**
     * value: "spanish"
     * @const
     */
    "spanish": "spanish",

    /**
     * value: "swedish"
     * @const
     */
    "swedish": "swedish",

    /**
     * value: "tamil"
     * @const
     */
    "tamil": "tamil",

    /**
     * value: "turkish"
     * @const
     */
    "turkish": "turkish",

    /**
     * value: "yiddish"
     * @const
     */
    "yiddish": "yiddish",

    /**
     * value: "simple"
     * @const
     */
    "simple": "simple"
};



export default IngestWebPageDocumentRequest;

