POST http://localhost:4000/v1/chat/completions
Content-Type: application/json

{
    "model": "llama3",
    "temperature": 0.5,
    "top_p": 1,
    "max_tokens": 1024,
    "messages": [
        {
            "role": "user",
            "content": "Write a limmerick about the wonders of GPU computing."
        }
    ],
    "metadata": {
        "session_id": "12345",
        "user_id": "user_abc",
        "tags": [
            "AI Empower Labs"
        ],
        "RAG_score": "0.8"
    }
}