/*
 * Studio - AI Empower Labs
 *
 * # Studio API Documentation  ## Introduction Welcome to Studio by AI Empower Labs API documentation! We are thrilled to offer developers around the world access to our cutting-edge artificial intelligence technology and semantic search. Our API is designed to empower your applications with state-of-the-art AI capabilities, including but not limited to natural language processing, audio transcription, embedding, and predictive analytics.  Our mission is to make AI technology accessible and easy to integrate, enabling you to enhance your applications, improve user experiences, and innovate in your field. Whether you're building complex systems, developing mobile apps, or creating web services, our API provides you with the tools you need to incorporate AI functionalities seamlessly.  Support and Feedback We are committed to providing exceptional support to our developer community. If you have any questions, encounter any issues, or have feedback on how we can improve our API, please don't hesitate to contact our support team @ support@AIEmpowerLabs.com.  Terms of Use Please review our terms of use and privacy policy before integrating our API into your application. By using our API, you agree to comply with these terms.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@aiempowerlabs.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TimeSpan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeSpanTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeSpan
        //private TimeSpan instance;

        public TimeSpanTests()
        {
            // TODO uncomment below to create an instance of TimeSpan
            //instance = new TimeSpan();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeSpan
        /// </summary>
        [Fact]
        public void TimeSpanInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeSpan
            //Assert.IsType<TimeSpan>(instance);
        }

        /// <summary>
        /// Test the property 'Ticks'
        /// </summary>
        [Fact]
        public void TicksTest()
        {
            // TODO unit test for the property 'Ticks'
        }

        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Fact]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }

        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Fact]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }

        /// <summary>
        /// Test the property 'Milliseconds'
        /// </summary>
        [Fact]
        public void MillisecondsTest()
        {
            // TODO unit test for the property 'Milliseconds'
        }

        /// <summary>
        /// Test the property 'Microseconds'
        /// </summary>
        [Fact]
        public void MicrosecondsTest()
        {
            // TODO unit test for the property 'Microseconds'
        }

        /// <summary>
        /// Test the property 'Nanoseconds'
        /// </summary>
        [Fact]
        public void NanosecondsTest()
        {
            // TODO unit test for the property 'Nanoseconds'
        }

        /// <summary>
        /// Test the property 'Minutes'
        /// </summary>
        [Fact]
        public void MinutesTest()
        {
            // TODO unit test for the property 'Minutes'
        }

        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

        /// <summary>
        /// Test the property 'TotalDays'
        /// </summary>
        [Fact]
        public void TotalDaysTest()
        {
            // TODO unit test for the property 'TotalDays'
        }

        /// <summary>
        /// Test the property 'TotalHours'
        /// </summary>
        [Fact]
        public void TotalHoursTest()
        {
            // TODO unit test for the property 'TotalHours'
        }

        /// <summary>
        /// Test the property 'TotalMilliseconds'
        /// </summary>
        [Fact]
        public void TotalMillisecondsTest()
        {
            // TODO unit test for the property 'TotalMilliseconds'
        }

        /// <summary>
        /// Test the property 'TotalMicroseconds'
        /// </summary>
        [Fact]
        public void TotalMicrosecondsTest()
        {
            // TODO unit test for the property 'TotalMicroseconds'
        }

        /// <summary>
        /// Test the property 'TotalNanoseconds'
        /// </summary>
        [Fact]
        public void TotalNanosecondsTest()
        {
            // TODO unit test for the property 'TotalNanoseconds'
        }

        /// <summary>
        /// Test the property 'TotalMinutes'
        /// </summary>
        [Fact]
        public void TotalMinutesTest()
        {
            // TODO unit test for the property 'TotalMinutes'
        }

        /// <summary>
        /// Test the property 'TotalSeconds'
        /// </summary>
        [Fact]
        public void TotalSecondsTest()
        {
            // TODO unit test for the property 'TotalSeconds'
        }
    }
}
