version: '3.8'  # Specifies the version of the Docker Compose file format

x-logging: &default-logging  # Defines a reusable logging configuration using YAML anchors
  options:
    max-size: "100m"  # Log rotation: max log size before rotation
    max-file: "5"  # Max number of log files to retain
  driver: json-file  # Specifies the logging driver, here using the default JSON file driver

services:  # Defines the services part of the compose file
  host:  # Service definition for the main application host
    image: registry.aiempowerlabs.com/aistudio:latest  # Specifies the Docker image to use
    logging: *default-logging  # Uses the defined reusable logging configuration
    restart: unless-stopped  # Restart policy: restart if the container stops unexpectedly
    ports:
      - "8080:8080"  # Port mapping: Maps port 8080 of the container to port 8080 on the host
    environment:
      configPath: /opt/aistudio/  # Environment variable specifying the config path inside the container
      ASPNETCORE_URLS: http://*:8080
    healthcheck:  # Health check using a curl command to a local endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8080/liveness"]
      interval: 1m
      timeout: 20s
      retries: 5
    volumes:
      - ./appsettings.json:/opt/aistudio/appsettings.json  # Mounts a configuration file into the container
    networks:
      - ai_internal  # Connects the service to the internal network
      - ai_public  # Connects the service to the public network
    depends_on:  # Specifies dependencies on other services
      - postgres
      - translation
      - transcription
      - embedding
      - llama3

  postgres:  # PostgreSQL database service
    image: ankane/pgvector:latest  # Image to use for PostgreSQL with vector extension
    logging: *default-logging
    restart: unless-stopped
    environment:  # Database credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:  # Checks the health of the service
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s  # Health check interval
      timeout: 3s  # Timeout for the health check
      retries: 3  # Number of retries before considering the service unhealthy
    networks:
      - ai_internal  # Connects the database service to the internal network only

  llama3:  # Service for LLM llama3
    image: registry.aiempowerlabs.com/llama3:latest
    logging: *default-logging
    restart: unless-stopped
    healthcheck:  # Health check using a curl command to a local endpoint
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 1m
      timeout: 20s
      retries: 5
    networks:
      - ai_internal  # Connects to the internal network

  translation:  # Translation service
    image: registry.aiempowerlabs.com/translation:latest  # Image to use for translation service
    logging: *default-logging  # Uses the reusable logging configuration
    restart: unless-stopped  # Restart policy: restart if the container stops unexpectedly
    healthcheck:  # Health check command to ensure service availability
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']     
    networks:
      - ai_internal  # Connects the service to the internal network only

  transcription:  # Transcription service
    image: registry.aiempowerlabs.com/transcription:latest  # Image to use for transcription service
    logging: *default-logging
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://*:8080
    healthcheck:  # Health check using a curl command to a local endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m  # Health check interval
      timeout: 10s  # Timeout for the health check
      retries: 3  # Number of retries before considering the service unhealthy
    networks:
      - ai_internal  # Connects to the internal network

  embedding:  # Embedding service
    image: registry.aiempowerlabs.com/multilingual-e5-large:latest  # Image to use for embedding service
    logging: *default-logging
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://*:8080
    healthcheck:  # Health check using a curl command to a local endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m  # Health check interval
      timeout: 10s  # Timeout for the health check
      retries: 3  # Number of retries before considering the service unhealthy
    networks:
      - ai_internal  # Connects to the internal network

networks:
  ai_public: {}  # Definition of the public network
  ai_internal: {}  # Definition of the internal network
