version: '3.8'
services:
  host:
    image: registry.aiempowerlabs.com/aistudio:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      configPath: /opt/aistudio/
    volumes:
      - ./appsettings.json:/opt/aistudio/appsettings.json
    depends_on:
      - postgres
      - translation
      - transcription
      - embedding
      - llama3

  postgres:
    image: ankane/pgvector:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3

  llama3:
    image: registry.aiempowerlabs.com/llama3:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 1m
      timeout: 20m
      retries: 5
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    security_opt:
      - label=disable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1  # Number of GPUs to use

  translation:
    image: registry.aiempowerlabs.com/translation:latest
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']     

  transcription:
    image: registry.aiempowerlabs.com/transcription:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3

  embedding:
    image: registry.aiempowerlabs.com/multilingual-e5-large:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
