/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DocumentPartition

class DocumentPartitionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DocumentPartition
        //val modelInstance = DocumentPartition()

        // to test the property `text` - Content of the document partition, aka chunk/block of text.
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `relevance` - Relevance of this partition against the given query.  Value usually is between 0 and 1, when using cosine similarity.
        should("test relevance") {
            // uncomment below to test the property
            //modelInstance.relevance shouldBe ("TODO")
        }

        // to test the property `lastUpdate` - Timestamp about the file/text partition.
        should("test lastUpdate") {
            // uncomment below to test the property
            //modelInstance.lastUpdate shouldBe ("TODO")
        }

        // to test the property `tags` - List of document tags
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
