/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.LanguageDetection

class LanguageDetectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LanguageDetection
        //val modelInstance = LanguageDetection()

        // to test the property `languageCode`
        should("test languageCode") {
            // uncomment below to test the property
            //modelInstance.languageCode shouldBe ("TODO")
        }

        // to test the property `confidence`
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

    }
}
