/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Partition

class PartitionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Partition
        //val modelInstance = Partition()

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `relevance`
        should("test relevance") {
            // uncomment below to test the property
            //modelInstance.relevance shouldBe ("TODO")
        }

        // to test the property `partitionNumber`
        should("test partitionNumber") {
            // uncomment below to test the property
            //modelInstance.partitionNumber shouldBe ("TODO")
        }

        // to test the property `sectionNumber`
        should("test sectionNumber") {
            // uncomment below to test the property
            //modelInstance.sectionNumber shouldBe ("TODO")
        }

        // to test the property `lastUpdate`
        should("test lastUpdate") {
            // uncomment below to test the property
            //modelInstance.lastUpdate shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
