/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.QueryDocumentRequest
import org.openapitools.client.models.DocumentFilters

class QueryDocumentRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryDocumentRequest
        //val modelInstance = QueryDocumentRequest()

        // to test the property `query` - Semantic query to find matching documents
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `index` - Optional index to specify which index to search in. Defaults to 'default'
        should("test index") {
            // uncomment below to test the property
            //modelInstance.index shouldBe ("TODO")
        }

        // to test the property `filter` - Optional filtering of document id(s) and/or tags
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `searchMode` - Optional search mode defining the context or process used in the query. Supported values are 'hybrid', 'semantic'
        should("test searchMode") {
            // uncomment below to test the property
            //modelInstance.searchMode shouldBe ("TODO")
        }

        // to test the property `language` - Specifies the language of the content.
        should("test language") {
            // uncomment below to test the property
            //modelInstance.language shouldBe ("TODO")
        }

        // to test the property `languageDetection` - Indicates whether language detection is enabled.
        should("test languageDetection") {
            // uncomment below to test the property
            //modelInstance.languageDetection shouldBe ("TODO")
        }

        // to test the property `ftsMinScore` - Minimum score for full-text search.
        should("test ftsMinScore") {
            // uncomment below to test the property
            //modelInstance.ftsMinScore shouldBe ("TODO")
        }

        // to test the property `ftsWeight` - Weight for full-text search.
        should("test ftsWeight") {
            // uncomment below to test the property
            //modelInstance.ftsWeight shouldBe ("TODO")
        }

        // to test the property `semanticMinRelevance` - Minimum relevance score for semantic search.
        should("test semanticMinRelevance") {
            // uncomment below to test the property
            //modelInstance.semanticMinRelevance shouldBe ("TODO")
        }

        // to test the property `semanticWeight` - Weight applied for semantic search.
        should("test semanticWeight") {
            // uncomment below to test the property
            //modelInstance.semanticWeight shouldBe ("TODO")
        }

        // to test the property `smoothingFactorK` - Smoothing factor (k) used in calculations.
        should("test smoothingFactorK") {
            // uncomment below to test the property
            //modelInstance.smoothingFactorK shouldBe ("TODO")
        }

        // to test the property `minRelevance` - Optional filter to specify minimum relevance. Typically values between 0 and 1
        should("test minRelevance") {
            // uncomment below to test the property
            //modelInstance.minRelevance shouldBe ("TODO")
        }

        // to test the property `limit` - Optional filter for specifying maximum number of entries to return. Defaults to 3
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `embeddingModel` - Embedding model to use in query
        should("test embeddingModel") {
            // uncomment below to test the property
            //modelInstance.embeddingModel shouldBe ("TODO")
        }

        // to test the property `args`
        should("test args") {
            // uncomment below to test the property
            //modelInstance.args shouldBe ("TODO")
        }

    }
}
