/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SemanticSimilarityRequest

class SemanticSimilarityRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SemanticSimilarityRequest
        //val modelInstance = SemanticSimilarityRequest()

        // to test the property `query` - Query text to compare with
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `documents`
        should("test documents") {
            // uncomment below to test the property
            //modelInstance.documents shouldBe ("TODO")
        }

        // to test the property `model`
        should("test model") {
            // uncomment below to test the property
            //modelInstance.model shouldBe ("TODO")
        }

    }
}
