/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TimeSpan

class TimeSpanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeSpan
        //val modelInstance = TimeSpan()

        // to test the property `ticks`
        should("test ticks") {
            // uncomment below to test the property
            //modelInstance.ticks shouldBe ("TODO")
        }

        // to test the property `days`
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `hours`
        should("test hours") {
            // uncomment below to test the property
            //modelInstance.hours shouldBe ("TODO")
        }

        // to test the property `milliseconds`
        should("test milliseconds") {
            // uncomment below to test the property
            //modelInstance.milliseconds shouldBe ("TODO")
        }

        // to test the property `microseconds`
        should("test microseconds") {
            // uncomment below to test the property
            //modelInstance.microseconds shouldBe ("TODO")
        }

        // to test the property `nanoseconds`
        should("test nanoseconds") {
            // uncomment below to test the property
            //modelInstance.nanoseconds shouldBe ("TODO")
        }

        // to test the property `minutes`
        should("test minutes") {
            // uncomment below to test the property
            //modelInstance.minutes shouldBe ("TODO")
        }

        // to test the property `seconds`
        should("test seconds") {
            // uncomment below to test the property
            //modelInstance.seconds shouldBe ("TODO")
        }

        // to test the property `totalDays`
        should("test totalDays") {
            // uncomment below to test the property
            //modelInstance.totalDays shouldBe ("TODO")
        }

        // to test the property `totalHours`
        should("test totalHours") {
            // uncomment below to test the property
            //modelInstance.totalHours shouldBe ("TODO")
        }

        // to test the property `totalMilliseconds`
        should("test totalMilliseconds") {
            // uncomment below to test the property
            //modelInstance.totalMilliseconds shouldBe ("TODO")
        }

        // to test the property `totalMicroseconds`
        should("test totalMicroseconds") {
            // uncomment below to test the property
            //modelInstance.totalMicroseconds shouldBe ("TODO")
        }

        // to test the property `totalNanoseconds`
        should("test totalNanoseconds") {
            // uncomment below to test the property
            //modelInstance.totalNanoseconds shouldBe ("TODO")
        }

        // to test the property `totalMinutes`
        should("test totalMinutes") {
            // uncomment below to test the property
            //modelInstance.totalMinutes shouldBe ("TODO")
        }

        // to test the property `totalSeconds`
        should("test totalSeconds") {
            // uncomment below to test the property
            //modelInstance.totalSeconds shouldBe ("TODO")
        }

    }
}
